name: publish npm
on:
  create:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Get the sources
      uses: actions/checkout@v2
    - name: Build and publish
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@kicaj29'        
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: cd my-workspace/
    - run: npm install
    - run: npm run build @kicaj29/lib1 --prod
    - run: cd dist/kicaj29/lib1
    - run: npm publish     